car_like_mobile_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30

  vehicle1_front_left_trans:
    type         : effort_controllers/JointEffortController
    joint        : vehicle1_front_left_joint
    pid          : {p: 100.0, i: 8.0, d: 20.0}
    publish_rate : 10

  vehicle1_front_left_steering_trans:
    type         : effort_controllers/JointPositionController
    joint        : vehicle1_front_left_steering_joint
    pid          : {p: 1000.0, i: 8.0, d: 0.0}
    publish_rate : 10

  vehicle1_front_right_trans:
    type         : effort_controllers/JointEffortController
    joint        : vehicle1_front_right_joint
    pid          : {p: 100.0, i: 8.0, d: 20.0}
    publish_rate : 10

  vehicle1_front_right_steering_trans:
    type         : effort_controllers/JointPositionController
    joint        : vehicle1_front_right_steering_joint
    pid          : {p: 1000.0, i: 8.0, d: 0.0}
    publish_rate : 10

  vehicle1_rear_left_trans:
    type         : effort_controllers/JointVelocityController
    joint        : vehicle1_rear_left_joint
    pid          : {p: 1000.0, i: 8.0, d: 0.0}
    publish_rate : 10

  vehicle1_rear_right_trans:
    type         : effort_controllers/JointVelocityController
    joint        : vehicle1_rear_right_joint
    pid          : {p: 1000.0, i: 8.0, d: 0.0}
    publish_rate : 10
