frequency: 50
sensor_timeout: 0.1
two_d_mode: true  # 2Dモード（ヨー角のみを考慮）
transform_time_offset: 0.0
transform_timeout: 0.0
print_diagnostics: true
publish_tf: true
publish_acceleration: false

map_frame: map
odom_frame: odom
base_link_frame: base_link
# world_frame: odom

odom0: odom0
odom0_config: [false, false, false,  # x, y, z
                false, false, false,    # roll, pitch, yaw
                true, false, false,  # vx, vy, vz
                false, false, false,  # vroll, vpitch, vyaw
                false, false, false]  # ax, ay, az

imu0: imu0
imu0_config: [false, false, false,  # x, y, z
              false, false, true,  # roll, pitch, yaw
              false,  false,  false,   # vx, vy, vz
              false,  false,  true,   # vroll, vpitch, vyaw
              false, false, false]  # ax, ay, az
imu0_differential: false
imu0_remove_gravitational_acceleration: true
