base_frame: base_link
map_frame: map
odom_frame: odom
map_update_interval: 1.0
# iterations: 5
# linearUpdate: 1.0
# angularUpdate: 0.5
temporalUpdate: 1.0
# resampleThreshold: 0.5
xmin: -20.0
xmax:  20.0
ymin: -20.0
ymax:  20.0