# Toolbox Params
odom_frame: "odom"
map_frame: "map"
base_frame: "base_link"
scan_topic: "/scan"
scan_queue_size: 1
use_map_saver: true
# map_file_name: "my_map"
# map_start_pose: [0.0, 0.0, 0.0]
# map_start_at_dock: false
# debug_logging: false
throttle_scans: 1
transform_publish_period: 0.1
map_update_interval: 1.0
enable_interactive_mode: true
position_covariance_scale: 1.0
yaw_covariance_scale: 0.1
resolution: 0.05
# max_laser_range: 30.0
# minimum_time_interval: 0.0
# transform_timeout: 0.2
# tf_buffer_duration: 10.0
# stack_size_to_use: 40000000
# minimum_travel_distance: 0.2

# Matcher Params
use_scan_matching: true
use_scan_barycenter: true
# minimum_travel_heading: 0.1
# scan_buffer_size: 100
# scan_buffer_maximum_scan_distance: 10.0
# link_match_minimum_response_fine: 0.6
# link_scan_maximum_distance: 10.0
# loop_search_maximum_distance: 10.0
do_loop_closing: true
# loop_match_minimum_chain_size: 10
# loop_match_maximum_variance_coarse: 0.6
# loop_match_minimum_response_coarse: 0.6
# loop_match_minimum_response_fine: 0.6
# correlation_search_space_dimension: 50.0
# correlation_search_space_resolution: 0.05
# correlation_search_space_smear_deviation: 0.03
# loop_search_space_dimension: 10.0
# loop_search_space_resolution: 0.05
# loop_search_space_smear_deviation: 0.03
# distance_variance_penalty: 1.0
# angle_variance_penalty: 0.5
# fine_search_angle_offset: 0.1
# coarse_search_angle_offset: 0.1
# coarse_angle_resolution: 0.08
# minimum_angle_penalty: 0.5
# minimum_distance_penalty: 0.5
# use_response_expansion: true
