# Toolbox Params
odom_frame: "odom"
map_frame: "map"
base_frame: "base_link"
scan_topic: "/scan"
scan_queue_size: 1
use_map_saver: true
# map_file_name: "my_map"
# map_start_pose: [0.0, 0.0, 0.0]
# map_start_at_dock: false
# debug_logging: false
throttle_scans: 1
transform_publish_period: 0.02
map_update_interval: 1.0
# enable_interactive_mode: true
# position_covariance_scale: 0.001
# yaw_covariance_scale: 0.001
resolution: 0.05
max_laser_range: 30.0
minimum_time_interval: 0.5
transform_timeout: 0.2
tf_buffer_duration: 30.0
stack_size_to_use: 40000000

# Matcher Params
use_scan_matching: true
use_scan_barycenter: true
minimum_travel_distance: 0.5
minimum_travel_heading: 0.5
scan_buffer_size: 3
scan_buffer_maximum_scan_distance: 10.0
link_match_minimum_response_fine: 0.1
link_scan_maximum_distance: 1.5
do_loop_closing: true
loop_match_minimum_chain_size: 3
loop_match_maximum_variance_coarse: 3.0
loop_match_minimum_response_coarse: 0.35
loop_match_minimum_response_fine: 0.45

correlation_search_space_dimension: 0.5
correlation_search_space_resolution: 0.01
correlation_search_space_smear_deviation: 0.1

loop_search_space_dimension: 8.0
loop_search_space_resolution: 0.05
loop_search_space_smear_deviation: 0.03
loop_search_maximum_distance: 3.0

distance_variance_penalty: 0.5
angle_variance_penalty: 1.0

fine_search_angle_offset: 0.00349     
coarse_search_angle_offset: 0.349   
coarse_angle_resolution: 0.0349        
minimum_angle_penalty: 0.9
minimum_distance_penalty: 0.5
use_response_expansion: true
